#!/bin/sh
set -e
set -u

# test to see whether we are running in 'development mode'
if [ "$0" = "./game-data-packager" ]; then
	GDP_UNINSTALLED=1
	export GDP_UNINSTALLED
	PYTHONPATH="$(pwd)"
else
	PYTHONPATH=/usr/share/games/game-data-packager
fi
export PYTHONPATH

# FIXME: undocumented feature currently disabled:
# python3 -m game_data_packager.make_template "$@"

exec python3 -m game_data_packager "$@"
