#!/bin/sh
set -e
set -u

# test to see whether we are running in 'development mode'
if [ "$0" = "./run" ]; then
	GDP_UNINSTALLED=1
	export GDP_UNINSTALLED
	PYTHONPATH="$(pwd)"
elif [ -d /usr/share/games/game-data-packager ]; then
	PYTHONPATH=/usr/share/games/game-data-packager
else
	PYTHONPATH=/usr/share/game-data-packager
fi
export PYTHONPATH

if [ $# -eq 0 ]; then
	exec python3 -m game_data_packager
fi

case "$1" in
	'make-template')
		shift
		exec python3 -m game_data_packager.make_template "$@"
		;;
	*)
		exec python3 -m game_data_packager "$@"
		;;
esac
