.TH doom2-master-levels 6 2015-04-18

.SH NAME
doom2\-masterlevels \- graphical launcher for DOOM II Master Levels
.
.SH SYNOPSIS
.B doom2\-masterlevels

.SH DESCRIPTION
This tool is a graphical interface that lets you
choose one of DOOM II's Master Levels, read its description
and start it with the Doom engine of your choice.

.SH OPTIONS
This tool is not really meant to be run from the command line,
and takes no options. If you want to pass custom command-line options to
the Doom engine, use the
.B doom
command directly.

.SH SEE ALSO
\fIdoom\fP(6)

.SH AUTHOR
Copyright \(co 2015 Alexandre Detiste \fI<alexandre@detiste.be>\fP
