#!/usr/bin/python3
# encoding=utf-8
#
# Copyright © 2015 Simon McVittie <smcv@debian.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# You can find the GPL license text on a Debian system under
# /usr/share/common-licenses/GPL-2.

if __name__ == '__main__':
    cin = open('debian/copyright.in')

    print(cin.__next__(), end='')
    print('# This file was generated by debian/copyright.py from debian/copyright.in')
    print('# Please edit one of those files instead')

    for line in cin:
        if line.lower().startswith('include-license:'):
            license = line.split(':', 1)[1].strip()
            for line in open(license):
                if line.strip():
                    print('  ' + line, end='')
                else:
                    print(' .')
        else:
            print(line, end='')
