README.quake3-data                      usr/share/games/quake3
build/48/quake3-teamarena.png           usr/share/icons/hicolor/48x48/apps
build/48/quake3.png                     usr/share/icons/hicolor/48x48/apps
build/quake3                            usr/games
build/quake3*.desktop                   usr/share/applications
build/quake3-teamarena.png              usr/share/icons/hicolor/256x256/apps
build/quake3.png                        usr/share/icons/hicolor/256x256/apps
need-data.sh                            usr/share/games/quake3
