.TH QUAKE3 6 "June 25 , 2008"
.SH NAME
quake3 \- Quake III Arena
.SH SYNOPSIS
.B quake3
[\-h|\-\-help] [\-q|\-\-quiet] [+set \fIoption\fP \fIvalue\fP]...
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B quake3
command.
.PP
\fBquake3\fP is the Quake III Arena client. It is a multiplayer network game.
.SH OPTIONS
Options passed to the wrapper script:
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a short help summary
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable all console output
.PP
Options that can be passed to the Quake III binary by the +set parameter
(note that this is not a full list!) include:
.PP
\fBcg_drawFPS\fR <bool>
.PP
\fBcg_drawTeamOverlay\fR <bool>
.PP
\fBcg_fov\fR <value>
.PP
\fBcg_lagometer\fR <bool>
.PP
\fBcg_shadows\fR <bool>
.PP
\fBcg_thirdPerson\fR <bool>
.PP
\fBcg_thirdPersonAngle\fR <value>
.PP
\fBcg_thirdPersonRange\fR <value>
.PP
\fBcg_zoomfov\fR <value>
.PP
\fBcl_mouseAccel\fR <bool>
.PP
\fBcom_blood\fR <bool>
.PP
\fBcom_hunkMegs\fR <value>
.PP
\fBcom_maxfps\fR <value>
.PP
\fBcom_soundMegs\fR <value>
.PP
\fBcom_zoneMegs\fR <value>
.PP
\fBfs_basepath\fR <string>
.PP
\fBfs_game\fR <string>
.PP
\fBr_allowExtensions\fR <bool>
.PP
\fBr_allowSoftwareGL\fR <bool>
.TP
\fBr_customheight\fR <value>
(Requires +set r_mode \-1)
.TP
\fBr_customwidth\fR <value>
(Requires +set r_mode \-1)
.PP
\fBr_dynamiclight\fR <bool>
.PP
\fBr_ext_compress_textures\fR <bool>
.PP
\fBr_ext_compressed_textures\fR <bool>
.PP
\fBr_fullscreen\fR <bool>
.PP
\fBr_ignoreGLErrors\fR <bool>
.PP
\fBr_mode\fR <value>
.BR
.SH FILES
.TP
\fI~/.q3a/baseq3\fR
Configuration and state for Quake III Arena
.TP
\fI~/.q3a/missionpack\fR
Configuration and state for Quake III: Team Arena, if installed
.SH ENVIRONMENT
.TP
\fBQUAKE3_DEBUGGER=\fIcommand\fR
A debugger or other prefix to prepend to the Quake III command line, such
as \fBstrace\fR; overridden by \fBQUAKE3_BACKTRACE\fR
.TP
\fBQUAKE3_BACKTRACE=1\fR
Use \fBgdb\fR(1) to get a backtrace if Quake III crashes (the \fBgdb\fR
package must be installed)
.SH SEE ALSO
.BR quake3-server (6)
.br
.SH AUTHOR
The Quake III Arena binary used is a modified ioQuake3; originally created by
Id Software, now maintained by the ioQuake3 community.
.PP
This manual page was written by Jack "jscinoz" Coulter <jscinoz@gmail.com> for the Debian project (but may be used by others). It is largely based off the manual page written by Bruno "Fuddl" Kleinert <fuddl@gmx.de> for the Debian project. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-2.
