#!/bin/sh

EXCUSE="\
Icculus.Org Quake III Arena server wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: ioquake3-server [OPTION]...\n\
\n\
 -h, --help\t\tDisplay this help\n\
 +set option value\tPass options to the Icculus.Org Quake III Arena server binary\n"

MISSING_FILES="\
Required Quake III data files are not installed.\n\
As root, run 'dpkg-reconfigure ioquake3-data'.\n"

# Quake 3 binaries don't understand "regular" command line parameters. Let's
# catch them here, to avoid accidently launching the binary.
while [ "$1" != "" ]; do {
	if [ "$1" == "+set" ]; then
		break;
	fi
	case "$1" in
		-h|--help)
			echo -e ${EXCUSE}
			exit 0;
			;;
	esac
}; done

# Is ioquake3-data configured?
for i in `seq -w 0 1 8`; do
	if [ ! -e /usr/lib/games/ioquake3/baseq3/pak$i.pk3 ]; then
		echo -e ${MISSING_FILES}
		exit 1;
	fi
done

# Ready to rumble!
cd /usr/lib/games/ioquake3
exec ./ioq3ded $*
exit $?
