#!/bin/sh

EXCUSE="\
Icculus.Org Quake III Arena client wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: ioquake3 [OPTION]...\n\
\n\
 -h, --help         Display this help\n\
 -q, --quiet        Disable console output\n\
 +<engine_command>  Pass options to the Icculus.Org Quake III Arena binary\n"

MISSING_FILES="\
Required Quake III data files are not installed.\n\
As root, run 'dpkg-reconfigure ioquake3-data'.\n"

QUIET=0

# Quake 3 binaries don't understand "regular" command line parameters. Let's
# catch them here, to avoid accidently launching the binary.
while [ "$1" != "" ]; do {
	if [ "$1" == "+set" ] || [ "$1" == "+exec" ]; then
		break;
	fi
	case "$1" in
		-h|--help)
			echo -e ${EXCUSE}
			exit 0
			;;
		-q|--quiet)
			QUIET=1
			;;
	esac
	shift
}; done

# Ready to rumble!
if [ ${QUIET} == 1 ]; then
	/usr/games/ioquake3.bin +set fs_basepath /usr/share/games/quake3 +set ttycon 0 $* >/dev/null 2>&1
else
	/usr/games/ioquake3.bin +set fs_basepath /usr/share/games/quake3 $*
fi
