#!/bin/sh

EXCUSE="\
Icculus.Org Quake III Arena client wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: ioquake3 [OPTION]...\n\
\n\
 -h, --help\t\tDisplay this help\n\
 -q, --quiet\t\tDisable console output\n\
 -s, --smp\t\tUse the SMP capable Icculus.Org Quake III Arena binary.\n\
\t\t\tREAD THE MANPAGE!\n\
 +set option value\tPass options to the Icculus.Org Quake III Arena binary\n"

MISSING_FILES="\
Required Quake III data files are not installed.\n\
As root, run 'dpkg-reconfigure ioquake3-data'.\n"

QUIET=0
BINARY=ioquake3

# Quake 3 binaries don't understand "regular" command line parameters. Let's
# catch them here, to avoid accidently launching the binary.

while [ "$1" != "" ]; do {
	if [ "$1" == "+set" ]; then
		break;
	fi
	case "$1" in
		-h|--help)
			echo -e ${EXCUSE}
			exit 0
			;;
		-q|--quiet)
			QUIET=1
			;;
		-s|--smp)
			BINARY=ioquake3-smp
			;;
	esac
	shift
}; done

# Is ioquake3-data configured?
for i in `seq -w 0 1 8`; do
	if [ ! -e /usr/lib/games/ioquake3/baseq3/pak$i.pk3 ]; then
		echo -e ${MISSING_FILES}
		exit 1;
	fi
done

# Ready to rumble!
cd /usr/lib/games/ioquake3

if [ ${QUIET} == 1 ]; then
	exec ./${BINARY} +set ttycon 0 $* >/dev/null 2>&1
else
	exec ./${BINARY} $*
fi

exit $?
