#!/bin/sh

EXCUSE="\
Icculus.Org Quake III Arena server wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: ioquake3-server [OPTION]...\n\
\n\
 -h, --help        Display this help\n\
 +<engine_command> Pass options to the Icculus.Org Quake 3 server binary\n"

MISSING_FILES="\
Required Quake III data files are not installed.\n\
As root, run 'dpkg-reconfigure quake3-data'.\n"

# ioQuake 3 binaries don't understand "regular" command line parameters. Let's
# catch them here, to avoid accidently launching the binary.
case "$1" in
	-h|--help)
		echo -e ${EXCUSE}
		exit 0;
		;;
esac

# Is quake3-data configured?
for i in `seq -w 0 1 8`; do
	if [ ! -e /usr/share/games/ioquake3/baseq3/pak$i.pk3 ]; then
		echo -e ${MISSING_FILES}
		exit 1;
	fi
done

# Ready to rumble!
/usr/games/ioq3ded.bin -basepath /usr/share/games/quake3-data $*
